### ISSUE TITLE
网站有时候一直在加载中

### ISSUE THREAD

**Issue by Judu233** [KuoKuo666/cocoscreator-examples#1]
cdn.jsdelivr.net 域名有时候访问不了，建议大佬改成fastly.jsdelivr.net试试
![image](https://user-images.githubusercontent.com/45262390/171595959-53b5d217-0727-424d-b492-6827dd0baa3f.png)

**Comment by KuoKuo666** [comment]
已经把对应的 js 迁移到自己网站了
